class GameConst {
    //滚动配置
    public static SPIN_RANDOM_SLOTS:string[] = [
        "DAEFDAEACSBFCBEDCDEEACCB123SBDBDBDFAFBAEASDBAA123CCBFSCFBECA",
        "123CBBFEASADFCDDEADBEBDBCADSAFFAEF123DESCBACACBBDCCEBFACEBDA",
        "DEDAEBFDCASDBCEASFADCA123AFDSEACACDCEECABE123SBFDBBDBBABCFCB"
    ]
}